//===================================================================
// COPYRIGHT Tony 2017/03/28
//===================================================================
// JNCITempTextRep.cpp
// Header definition of class JNCITempTextRep
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/03/28 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef JNCITempTextRep_H
#define JNCITempTextRep_H

#include "VisTempRepMod.h"
#include "CATBaseUnknown.h"

//Mathematics 
#include "CATMathPoint.h"
#include "CATMathPlane.h"

//VisualizationFoundation 
#include "CATRep.h"

#include "CATUnicodeString.h"

extern ExportedByVisTempRepMod  IID IID_JNCITempTextRep ;


class ExportedByVisTempRepMod JNCITempTextRep: public CATBaseUnknown
{
CATDeclareInterface;

public:

	virtual HRESULT CreateDefaultTypeText(CATMathPoint iOrigin,CATUnicodeString  strText) = 0;

	virtual HRESULT SetGraphicRepresentation (CATRep *  iRep ) = 0;

	virtual HRESULT GetGraphicRepresentation (CATRep **  oRep) = 0;

	virtual HRESULT GetInformation(CATMathPoint& oOrigin,CATUnicodeString& strText ) = 0;
};

//-----------------------------------------------------------------------
CATDeclareHandler( JNCITempTextRep, CATBaseUnknown );

#endif
