//===================================================================
// COPYRIGHT Tony 2017/03/28
//===================================================================
// JNCITempWireBoxRep.cpp
// Header definition of class JNCITempWireBoxRep
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/03/28 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef JNCITempWireBoxRep_H
#define JNCITempWireBoxRep_H

#include "VisTempRepMod.h"
#include "CATBaseUnknown.h"

//Mathematics 
#include "CATMathPoint.h"
#include "CATMathPlane.h"

extern ExportedByVisTempRepMod  IID IID_JNCITempWireBoxRep ;


class ExportedByVisTempRepMod JNCITempWireBoxRep: public CATBaseUnknown
{
CATDeclareInterface;

public:

	virtual HRESULT SetDimBox ( const float iDimBox ) = 0;
	virtual HRESULT GetDimBox (float * oDimBox ) = 0;

	virtual HRESULT SetCenterBox(const CATMathPoint & iCenter)  =0 ;
	virtual HRESULT GetCenterBox(CATMathPoint & oCenter) const  =0 ;

	virtual HRESULT SetLowAndHigh ( const CATMathPoint & iLow, const CATMathPoint & iHigh ) = 0;
	virtual HRESULT GetLowAndHigh( CATMathPoint & iLow, CATMathPoint & iHigh) const = 0;

	virtual int GetMode() = 0;
};

//-----------------------------------------------------------------------

CATDeclareHandler( JNCITempWireBoxRep, CATBaseUnknown );

#endif
