//===================================================================
// COPYRIGHT Tony 2017/09/05
//===================================================================
// JNCITempCircleRep.cpp
// Header definition of class JNCITempCircleRep
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/09/05 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef JNCITempCircleRep_H
#define JNCITempCircleRep_H

#include "VisTempRepMod.h"
#include "CATBaseUnknown.h"


extern ExportedByVisTempRepMod  IID IID_JNCITempCircleRep ;


class ExportedByVisTempRepMod JNCITempCircleRep: public CATBaseUnknown
{
CATDeclareInterface;

public:

};

//-----------------------------------------------------------------------
CATDeclareHandler( JNCITempCircleRep, CATBaseUnknown );

#endif
