//===================================================================
// COPYRIGHT Tony 2017/04/17
//===================================================================
// JNCITempPointRep.cpp
// Header definition of class JNCITempPointRep
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/04/17 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef JNCITempPointRep_H
#define JNCITempPointRep_H

#include "VisTempRepMod.h"
#include "CATBaseUnknown.h"

//Mathematics 
#include "CATMathPoint.h"
#include "CATMathDirection.h"

//VisualizationFoundation 
#include "CATRep.h"

//VisualizationCore
#include "CATSymbolType.h"

extern ExportedByVisTempRepMod  IID IID_JNCITempPointRep ;


class ExportedByVisTempRepMod JNCITempPointRep: public CATBaseUnknown
{
CATDeclareInterface;

public:

	virtual HRESULT CreateDefaultPoint(CATMathPoint *iOrigin,int color1=0,int color2=255,int color3=0, CATSymbolType SymType = CROSS) = 0;

	virtual HRESULT SetGraphicRepresentation (CATRep *  iRep ) = 0;

	virtual HRESULT GetGraphicRepresentation (CATRep **  oRep ) = 0;

	virtual HRESULT GetPoint(CATMathPoint &ioMathPoint) = 0;

};

//-----------------------------------------------------------------------
CATDeclareHandler( JNCITempPointRep, CATBaseUnknown );

#endif
