//===================================================================
// COPYRIGHT Tony 2017/03/28
//===================================================================
// VisTempRepMod.cpp
// Header definition of class VisTempRepMod
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/03/28 Creation: Code generated by the 3DS wizard
//===================================================================
#ifdef  _WINDOWS_SOURCE
#ifdef  __VisTempRepMod
#define ExportedByVisTempRepMod     __declspec(dllexport)
#else
#define ExportedByVisTempRepMod     __declspec(dllimport)
#endif
#else
#define ExportedByVisTempRepMod
#endif
