// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module CommonFuncMod
#======================================================================
#  2016/11/18 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = $(WIZARD_LINK_MODULES)
# DO NOT EDIT :: 3DS WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  JS0FM \
JS0GROUP \
DI0PANV2 \
CATPLMComponentInterfaces \
ObjectModelerSystem \
CATMecModLiveUseItf \
CATMecModUseItf \
KnowledgeItf \
CAT3DPhysicalRepItf \
CATAfrFoundation \
CATMathematics \
CATPLMModelerBaseInterfaces \
CATGMModelInterfaces \
CATGMGeometricInterfaces \
CATMeasureGeometryInterfaces \
CATGeometricObjects \
CATProductStructureInterfaces \
CATProductStructureUseItf \
CATEngConnectionUseItf \
CATAssemblyConstraintUseItf \
CATPLMUpdateUseItf \
CATObjectModelerBase \
CATAfrNavigator \
CATObjectModelerNavigator \
CATPLMBatch \
CATPLMIntegrationAccess \
CatXmlItfExt \
CatXmlItfBase \
CATVisItf \
CATGMOperatorsInterfaces \
CATMathStream \
VPMEditorInterfaces \
CATVisFoundation \
CATVisController \
CATSysTS \
CATPLMIdentificationAccess \

# END WIZARD EDITION ZONE
