//===================================================================
// COPYRIGHT Tony 2017/03/28
//===================================================================
// JNCITempTextRep.cpp
// Header definition of class JNCITempTextRep
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/03/28 Creation: Code generated by the 3DS wizard
//===================================================================
#include "CATMetaClass.h"
#include "JNCITempTextRep.h"


#ifndef LOCAL_DEFINITION_FOR_IID
IID IID_JNCITempTextRep = {0xd6b17bfe,0x7d72,0x44b6,{ 0xa7,0x88,0x52,0x50,0xf3,0x4a,0x59,0x92}};
#endif

CATImplementInterface(JNCITempTextRep, CATBaseUnknown);
CATImplementHandler(JNCITempTextRep, CATBaseUnknown);
