//===================================================================
// COPYRIGHT Tony 2017/04/17
//===================================================================
// JNCITempPointRep.cpp
// Header definition of class JNCITempPointRep
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/04/17 Creation: Code generated by the 3DS wizard
//===================================================================
#include "CATMetaClass.h"
#include "JNCITempPointRep.h"


#ifndef LOCAL_DEFINITION_FOR_IID
IID IID_JNCITempPointRep = {0xb981e7de,0x1c2f,0x4713,{ 0x8f,0x3c,0x85,0x5f,0x4a,0x85,0x2f,0x09}};
#endif

CATImplementInterface(JNCITempPointRep, CATBaseUnknown);
CATImplementHandler(JNCITempPointRep, CATBaseUnknown);
