//===================================================================
// COPYRIGHT Tony 2017/03/28
//===================================================================
// JNCITempWireBoxRep.cpp
// Header definition of class JNCITempWireBoxRep
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/03/28 Creation: Code generated by the 3DS wizard
//===================================================================
#include "CATMetaClass.h"
#include "JNCITempWireBoxRep.h"


#ifndef LOCAL_DEFINITION_FOR_IID
IID IID_JNCITempWireBoxRep = {0x6e4d2147,0x8b9e,0x45fb,{ 0x9d,0xf2,0x95,0x1b,0xaf,0x29,0x1e,0x69}};
#endif

CATImplementInterface(JNCITempWireBoxRep, CATBaseUnknown);
CATImplementHandler(JNCITempWireBoxRep, CATBaseUnknown);