//===================================================================
// COPYRIGHT Tony 2017/03/29
//===================================================================
// JNCITempFixArrrowRep.cpp
// Header definition of class JNCITempFixArrrowRep
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/03/29 Creation: Code generated by the 3DS wizard
//===================================================================
#include "CATMetaClass.h"
#include "JNCITempFixArrowRep.h"


#ifndef LOCAL_DEFINITION_FOR_IID
IID IID_JNCITempFixArrowRep = {0x451b65a0,0xcd13,0x4af0,{ 0xa2,0xc9,0x30,0x70,0x48,0x1e,0xaa,0x52}};
#endif

CATImplementInterface(JNCITempFixArrowRep, CATBaseUnknown);
CATImplementHandler(JNCITempFixArrowRep, CATBaseUnknown);
