//===================================================================
// COPYRIGHT Tony 2017/09/05
//===================================================================
// JNCITempCircleRep.cpp
// Header definition of class JNCITempCircleRep
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/09/05 Creation: Code generated by the 3DS wizard
//===================================================================
#include "CATMetaClass.h"
#include "JNCITempCircleRep.h"


#ifndef LOCAL_DEFINITION_FOR_IID
IID IID_JNCITempCircleRep = {0x790b3883,0x6250,0x4fd1,{ 0x8c,0x08,0x9a,0x08,0x34,0xe4,0xff,0x90}};
#endif

CATImplementInterface(JNCITempCircleRep, CATBaseUnknown);
CATImplementHandler(JNCITempCircleRep, CATBaseUnknown);
