//===================================================================
// COPYRIGHT Tony 2017/04/17
//===================================================================
// JNCTempPointRepInstance.cpp
// Header definition of class JNCTempPointRepInstance
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/04/17 Creation: Code generated by the 3DS wizard
//===================================================================

#include "JNCTempPointRepInstance.h"

#include "JNCTempPointRepComp.h"

CATImplementClass(JNCTempPointRepInstance,CodeExtension,CATBaseUnknown,JNCTempPointRepComp);

#include "TIE_CATICreateInstance.h"
TIE_CATICreateInstance(JNCTempPointRepInstance);


//-----------------------------------------------------------------------------
// JNCTempPointRepInstance : constructor
//-----------------------------------------------------------------------------
JNCTempPointRepInstance::JNCTempPointRepInstance():CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// JNCTempPointRepInstance : destructor
//-----------------------------------------------------------------------------
JNCTempPointRepInstance::~JNCTempPointRepInstance()
{
}



//------------------------------------
//	CATICreateInstance
//------------------------------------
HRESULT JNCTempPointRepInstance:: CreateInstance(void **oPPV) 
{
	JNCTempPointRepComp *pComp = new JNCTempPointRepComp();
	if( NULL == pComp ) return (E_OUTOFMEMORY);

	*oPPV = (void *)pComp;

	return S_OK;
} 






