//===================================================================
// COPYRIGHT Tony 2017/03/29
//===================================================================
// JNCTempFixArrowRepInstance.cpp
// Header definition of class JNCTempFixArrowRepInstance
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/03/29 Creation: Code generated by the 3DS wizard
//===================================================================

#include "JNCTempFixArrowRepInstance.h"

#include "JNCTempFixArrowRepComp.h"

CATImplementClass(JNCTempFixArrowRepInstance,CodeExtension,CATBaseUnknown,JNCTempFixArrowRepComp);

#include "TIE_CATICreateInstance.h"
TIE_CATICreateInstance(JNCTempFixArrowRepInstance);


//-----------------------------------------------------------------------------
// JNCTempFixArrowRepInstance : constructor
//-----------------------------------------------------------------------------
JNCTempFixArrowRepInstance::JNCTempFixArrowRepInstance():CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// JNCTempFixArrowRepInstance : destructor
//-----------------------------------------------------------------------------
JNCTempFixArrowRepInstance::~JNCTempFixArrowRepInstance()
{
}



//------------------------------------
//	CATICreateInstance
//------------------------------------
HRESULT JNCTempFixArrowRepInstance:: CreateInstance(void **oPPV)
{
	JNCTempFixArrowRepComp *pComp = new JNCTempFixArrowRepComp();
	if( NULL == pComp ) return (E_OUTOFMEMORY);

	*oPPV = (void *)pComp;

	return S_OK;
} 






