//===================================================================
// COPYRIGHT Tony 2017/03/28
//===================================================================
// JNCTempWireBoxComp.cpp
// Header definition of class JNCTempWireBoxComp
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/03/28 Creation: Code generated by the 3DS wizard
//===================================================================

#include "JNCTempWireBoxComp.h"

CATImplementClass(JNCTempWireBoxComp,Implementation,CATBaseUnknown,CATNull);

#include "TIE_JNCITempWireBoxRep.h"
TIE_JNCITempWireBoxRep(JNCTempWireBoxComp);


//-----------------------------------------------------------------------------
// JNCTempWireBoxComp : constructor
//-----------------------------------------------------------------------------
JNCTempWireBoxComp::JNCTempWireBoxComp():CATBaseUnknown(),_DimBox(0.2f) 
{
}

//-----------------------------------------------------------------------------
// JNCTempWireBoxComp : destructor
//-----------------------------------------------------------------------------
JNCTempWireBoxComp::~JNCTempWireBoxComp()
{
}


//------------------------------------
//	JNCITempWireBoxRep
//------------------------------------
HRESULT JNCTempWireBoxComp::SetDimBox ( const float iDim ) 
{
	_DimBox = iDim ;
	_Mode = 0;
	return S_OK;
} 


HRESULT JNCTempWireBoxComp::GetDimBox (float * oDim ) 
{
	if ( NULL == oDim ) 
		return E_FAIL;
	*oDim = _DimBox;
	return S_OK;
} 

HRESULT JNCTempWireBoxComp::SetCenterBox(const CATMathPoint & iCenter)  
{
	_CenterBox = iCenter ;
	_Mode = 0;
	return S_OK;
}  

HRESULT JNCTempWireBoxComp::GetCenterBox(CATMathPoint & oCenter) const  
{
	oCenter = _CenterBox ;
	return S_OK;
}  

HRESULT JNCTempWireBoxComp::SetLowAndHigh( const CATMathPoint & iLow, const CATMathPoint & iHigh )
{
	_LowBox = iLow;
	_HightBox = iHigh;
	_Mode = 1;

	return S_OK;
}

HRESULT JNCTempWireBoxComp::GetLowAndHigh( CATMathPoint & iLow, CATMathPoint & iHigh ) const
{
	iLow = _LowBox;
	iHigh = _HightBox;

	return S_OK;
}

int JNCTempWireBoxComp::GetMode()
{
	return _Mode;
}






