//===================================================================
// COPYRIGHT Tony 2017/03/28
//===================================================================
// JNCTempWireBoxInstance.cpp
// Header definition of class JNCTempWireBoxInstance
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/03/28 Creation: Code generated by the 3DS wizard
//===================================================================

#include "JNCTempWireBoxInstance.h"

#include "JNCTempWireBoxComp.h"

CATImplementClass(JNCTempWireBoxInstance,CodeExtension,CATBaseUnknown,JNCTempWireBoxComp);

#include "TIE_CATICreateInstance.h"
TIE_CATICreateInstance(JNCTempWireBoxInstance);

#include "iostream.h"
//-----------------------------------------------------------------------------
// JNCTempWireBoxInstance : constructor
//-----------------------------------------------------------------------------
JNCTempWireBoxInstance::JNCTempWireBoxInstance():CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// JNCTempWireBoxInstance : destructor
//-----------------------------------------------------------------------------
JNCTempWireBoxInstance::~JNCTempWireBoxInstance()
{
}



//------------------------------------
//	CATICreateInstance
//------------------------------------
HRESULT JNCTempWireBoxInstance:: CreateInstance(void **oPPV) 
{
	JNCTempWireBoxComp * pt = new JNCTempWireBoxComp();
	if ( NULL == pt) 
		return(E_OUTOFMEMORY);

	*oPPV = (void *)pt;

	return S_OK;
} 






