//===================================================================
// COPYRIGHT Tony 2017/03/28
//===================================================================
// JNCTempTextRepInstance.cpp
// Header definition of class JNCTempTextRepInstance
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/03/28 Creation: Code generated by the 3DS wizard
//===================================================================

#include "JNCTempTextRepInstance.h"
#include "JNCTempTextRepComp.h"

CATImplementClass(JNCTempTextRepInstance,CodeExtension,CATBaseUnknown,JNCTempTextRepComp);

#include "TIE_CATICreateInstance.h"
TIE_CATICreateInstance(JNCTempTextRepInstance);


//-----------------------------------------------------------------------------
// JNCTempTextRepInstance : constructor
//-----------------------------------------------------------------------------
JNCTempTextRepInstance::JNCTempTextRepInstance():CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// JNCTempTextRepInstance : destructor
//-----------------------------------------------------------------------------
JNCTempTextRepInstance::~JNCTempTextRepInstance()
{
}



//------------------------------------
//	CATICreateInstance
//------------------------------------
HRESULT JNCTempTextRepInstance:: CreateInstance(void **oPPV) 
{
	JNCTempTextRepComp * pt = new JNCTempTextRepComp();
	if (NULL == pt) return(E_OUTOFMEMORY);
	*oPPV = (void *)pt;
	return(S_OK);
} 






