//===================================================================
// COPYRIGHT Tony 2016/11/22
//===================================================================
// ExcelHandler.cpp
// Header definition of class ExcelHandler
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2016/11/22 Creation: Code generated by the 3DS wizard
//===================================================================
#ifdef  _WINDOWS_SOURCE
#ifdef  __ExcelHandler
#define ExportedByExcelHandler     __declspec(dllexport)
#else
#define ExportedByExcelHandler     __declspec(dllimport)
#endif
#else
#define ExportedByExcelHandler
#endif
