//===================================================================
// COPYRIGHT Tony 2016/11/22
//===================================================================
// MakeExcel.cpp
// Header definition of class MakeExcel
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2016/11/22 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef MakeExcel_H
#define MakeExcel_H

// System
#include "CATBaseUnknown.h"
#include "CATUnicodeString.h"

//#pragma once
#include "ExcelHandler.h"

#import "C:\Program Files\Common Files\Microsoft Shared\OFFICE14\MSO.DLL" rename("RGB","msoRGB") rename ("SearchPath","msoSearchPath") rename ("DocumentProperties","MSODocumentProperties") 
using namespace Office;

#import "C:\Program Files (x86)\Common Files\microsoft shared\VBA\VBA6\VBE6EXT.OLB" 
using namespace VBIDE;

#import "C:\Program Files\Microsoft Office\Office14\EXCEL.EXE" rename("DialogBox","ExcelDialogBox") rename("RGB","ExcelRGB") rename("CopyFile","ExcelCopyFile") rename("ReplaceText","ExcelReplaceText") no_auto_exclude 
using namespace Excel;

//-----------------------------------------------------------------------
/**
* Generate an Excel, just for test use.
* @param ExcelName
*   The file name, file will be generated at E:\\
*/
ExportedByExcelHandler HRESULT Generate(const CATUnicodeString &ExcelName);


//-----------------------------------------------------------------------

#endif
