//===================================================================
// COPYRIGHT Tony 2016/11/21
//===================================================================
// SQLHandler.cpp
// Header definition of class SQLHandler
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2016/11/21 Creation: Code generated by the 3DS wizard
//===================================================================
#ifdef  _WINDOWS_SOURCE
#ifdef  __SQLHandler
#define ExportedBySQLHandler     __declspec(dllexport)
#else
#define ExportedBySQLHandler     __declspec(dllimport)
#endif
#else
#define ExportedBySQLHandler
#endif
