
//===================================================================
// COPYRIGHT Tony 2017/03/28
//===================================================================
// JNCETempWireBoxVisu.cpp
// Header definition of class JNCETempWireBoxVisu
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/03/28 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef JNCETempWireBoxVisu_H
#define JNCETempWireBoxVisu_H

#include "CATBaseUnknown.h"

// Visualization Framework
#include "CATExtIVisu.h" 

//-----------------------------------------------------------------------

class JNCETempWireBoxVisu: public CATExtIVisu

{
CATDeclareClass;

public:

	// Standard constructors and destructors
	// -------------------------------------
	JNCETempWireBoxVisu ();
	virtual ~JNCETempWireBoxVisu ();

	virtual  CATRep * BuildRep();

private:
	// Copy constructor and equal operator
	// -----------------------------------
	JNCETempWireBoxVisu (JNCETempWireBoxVisu &);
	JNCETempWireBoxVisu& operator=(JNCETempWireBoxVisu&);
};

//-----------------------------------------------------------------------

#endif

