
//===================================================================
// COPYRIGHT Tony 2017/03/29
//===================================================================
// JNCTempFixArrowRepComp.cpp
// Header definition of class JNCTempFixArrowRepComp
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/03/29 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef JNCTempFixArrowRepComp_H
#define JNCTempFixArrowRepComp_H

#include "CATModelForRep3D.h"


//Mathematics 
#include "CATMathPoint.h"
#include "CATMathDirection.h"

//VisualizationFoundation 
#include "CATRep.h"
#include "CAT3DFixedArrowGP.h"
#include "CAT3DCustomRep.h"

//AfrFoundation 
#include "CATFrmEditor.h"
#include "CATISO.h"

//-----------------------------------------------------------------------

class JNCTempFixArrowRepComp: public CATModelForRep3D

{
CATDeclareClass;

public:

	// Standard constructors and destructors
	// -------------------------------------
	JNCTempFixArrowRepComp ();
	virtual ~JNCTempFixArrowRepComp ();

public:

	virtual HRESULT CreateDefaultTypeFixArrow(CATMathPoint *iOrigin,CATMathDirection * iDir,int color1 = 0,int color2=255,int color3 = 0) ;

	virtual HRESULT ChangeDefaultTypeFixArrow (CATMathPoint *iOrigin, CATMathDirection * iDir,int color1 = 0,int color2=255,int color3 = 0) ;

	virtual HRESULT SetGraphicRepresentation (CATRep *  iRep ) ;

	virtual HRESULT GetGraphicRepresentation (CATRep **  oRep ) ;

	virtual HRESULT GetOriginalPoint(CATMathPoint &iMathPoint) ;

	virtual HRESULT GetAlignDir(CATMathDirection &iMathDir) ;


private:
	// Copy constructor and equal operator
	// -----------------------------------
	JNCTempFixArrowRepComp (JNCTempFixArrowRepComp &);
	JNCTempFixArrowRepComp& operator=(JNCTempFixArrowRepComp&);

	CATMathPoint		_mathPt;
	CATMathDirection	_mathDir;
};

//-----------------------------------------------------------------------

#endif

