
//===================================================================
// COPYRIGHT Tony 2017/03/28
//===================================================================
// JNCTempTextRepInstance.cpp
// Header definition of class JNCTempTextRepInstance
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/03/28 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef JNCTempTextRepInstance_H
#define JNCTempTextRepInstance_H

#include "CATBaseUnknown.h"

//-----------------------------------------------------------------------

class JNCTempTextRepInstance: public CATBaseUnknown

{
CATDeclareClass;

public:

	// Standard constructors and destructors
	// -------------------------------------
	JNCTempTextRepInstance ();
	virtual ~JNCTempTextRepInstance ();


    virtual HRESULT __stdcall CreateInstance(void **oPPV) ;


private:
	// Copy constructor and equal operator
	// -----------------------------------
	JNCTempTextRepInstance (JNCTempTextRepInstance &);
	JNCTempTextRepInstance& operator=(JNCTempTextRepInstance&);
};

//-----------------------------------------------------------------------

#endif

