
//===================================================================
// COPYRIGHT Tony 2017/03/28
//===================================================================
// JNCTempWireBoxInstance.cpp
// Header definition of class JNCTempWireBoxInstance
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/03/28 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef JNCTempWireBoxInstance_H
#define JNCTempWireBoxInstance_H

#include "CATBaseUnknown.h"

//-----------------------------------------------------------------------

class JNCTempWireBoxInstance: public CATBaseUnknown

{
CATDeclareClass;

public:
	// Standard constructors and destructors
	// -------------------------------------
	JNCTempWireBoxInstance ();
	virtual ~JNCTempWireBoxInstance ();


    virtual HRESULT __stdcall CreateInstance(void **oPPV) ;


private:
	// Copy constructor and equal operator
	// -----------------------------------
	JNCTempWireBoxInstance (JNCTempWireBoxInstance &);
	JNCTempWireBoxInstance& operator=(JNCTempWireBoxInstance&);
};

//-----------------------------------------------------------------------

#endif

