
//===================================================================
// COPYRIGHT Tony 2017/04/17
//===================================================================
// JNCTempPointRepInstance.cpp
// Header definition of class JNCTempPointRepInstance
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/04/17 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef JNCTempPointRepInstance_H
#define JNCTempPointRepInstance_H

#include "CATBaseUnknown.h"

//-----------------------------------------------------------------------

class JNCTempPointRepInstance: public CATBaseUnknown

{
CATDeclareClass;

public:

	// Standard constructors and destructors
	// -------------------------------------
	JNCTempPointRepInstance ();
	virtual ~JNCTempPointRepInstance ();


    virtual HRESULT __stdcall CreateInstance(void **oPPV) ;


private:
	// Copy constructor and equal operator
	// -----------------------------------
	JNCTempPointRepInstance (JNCTempPointRepInstance &);
	JNCTempPointRepInstance& operator=(JNCTempPointRepInstance&);
};

//-----------------------------------------------------------------------

#endif

