
//===================================================================
// COPYRIGHT Tony 2017/03/29
//===================================================================
// JNCTempFixArrowRepInstance.cpp
// Header definition of class JNCTempFixArrowRepInstance
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/03/29 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef JNCTempFixArrowRepInstance_H
#define JNCTempFixArrowRepInstance_H

#include "CATBaseUnknown.h"

//-----------------------------------------------------------------------

class JNCTempFixArrowRepInstance: public CATBaseUnknown

{
CATDeclareClass;

public:

	// Standard constructors and destructors
	// -------------------------------------
	JNCTempFixArrowRepInstance ();
	virtual ~JNCTempFixArrowRepInstance ();

    virtual HRESULT __stdcall CreateInstance(void **oPPV) ;

private:
	// Copy constructor and equal operator
	// -----------------------------------
	JNCTempFixArrowRepInstance (JNCTempFixArrowRepInstance &);
	JNCTempFixArrowRepInstance& operator=(JNCTempFixArrowRepInstance&);
};

//-----------------------------------------------------------------------

#endif

