
//===================================================================
// COPYRIGHT Tony 2017/03/28
//===================================================================
// JNCTempWireBoxComp.cpp
// Header definition of class JNCTempWireBoxComp
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/03/28 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef JNCTempWireBoxComp_H
#define JNCTempWireBoxComp_H

#include "CATBaseUnknown.h"

#include "CATMathPoint.h" 

//-----------------------------------------------------------------------

class JNCTempWireBoxComp: public CATBaseUnknown

{
CATDeclareClass;

public:

	// Standard constructors and destructors
	// -------------------------------------
	JNCTempWireBoxComp ();
	virtual ~JNCTempWireBoxComp ();


	virtual HRESULT SetDimBox ( const float iDimBox ) ;

	virtual HRESULT GetDimBox (float * oDimBox ) ;

	virtual HRESULT SetLowAndHigh ( const CATMathPoint & iLow, const CATMathPoint & iHigh ) ;

	virtual HRESULT GetLowAndHigh( CATMathPoint & iLow, CATMathPoint & iHigh) const   ;

	virtual HRESULT SetCenterBox(const CATMathPoint & iCenter)   ;

	virtual HRESULT GetCenterBox(CATMathPoint & oCenter) const   ;

	virtual int GetMode();


private:
	// Copy constructor and equal operator
	// -----------------------------------
	JNCTempWireBoxComp (JNCTempWireBoxComp &);
	JNCTempWireBoxComp& operator=(JNCTempWireBoxComp&);

	float        _DimBox ;
	CATMathPoint _CenterBox ;
	CATMathPoint _LowBox;
	CATMathPoint _HightBox;
	int			 _Mode;
};

//-----------------------------------------------------------------------

#endif

