//===================================================================
// COPYRIGHT JN 2016/11/18
//===================================================================
// CommonFuncMod.cpp
// Header definition of class CommonFuncMod
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2016/11/18 Creation: Code generated by the 3DS wizard
//===================================================================
#ifdef  _WINDOWS_SOURCE
#ifdef  __CommonFuncMod
#define ExportedByCommonFuncMod     __declspec(dllexport)
#else
#define ExportedByCommonFuncMod     __declspec(dllimport)
#endif
#else
#define ExportedByCommonFuncMod
#endif
