//===================================================================
// COPYRIGHT JIT 2018/05/14
//===================================================================
// CommonToolMod.cpp
// Header definition of class CommonToolMod
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2018/05/14 Creation: Code generated by the 3DS wizard
//===================================================================
#ifdef  _WINDOWS_SOURCE
#ifdef  __CommonToolMod
#define ExportedByJCommonToolMod     __declspec(dllexport)
#else
#define ExportedByCommonToolMod     __declspec(dllimport)
#endif
#else
#define ExportedByCommonToolMod
#endif
