//===================================================================
// COPYRIGHT Tony 2017/03/24
//===================================================================
// TopologyEnhancement.cpp
// Header definition of class TopologyEnhancement
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2017/03/24 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef TopologyEnhancement_H
#define TopologyEnhancement_H

#include "CommonFuncMod.h"

#include "CATBaseUnknown.h"
#include "CATLISTV_CATBaseUnknown.h"

#include "CATIBodyRequest.h"

#include "CATMathPoint.h"
#include "CATMathTransformation.h"
#include "CATBody.h"
#include "CATCell.h"
#include "CATIMmiUseMfBRep.h"
#include "CATIMmiUseGeometricalElement.h"
#include "CATBody.h"
#include "CATCell.h"
#include "CATGeometry.h"
#include "CATTopData.h"
#include "CATTransfoManager.h"
#include "CATCGMContainerMngt.h"
#include "CATICGMDistancePointBody.h"
#include "CATIPLMNavReference.h"
#include "CATSoftwareConfiguration.h"
#include "CATICGMDistanceMinBodyBody.h"
#include "CATICGMDistanceBodyBody.h"
#include "CATICGMTopPointOperator.h"
//-----------------------------------------------------------------------

namespace JNCTonySpace{

	ExportedByCommonFuncMod CATBody_var GetBodyFromFeature(CATBaseUnknown_var ispBaseKnown);

	ExportedByCommonFuncMod HRESULT GetDistanceBetweenCellLists( CATLISTP(CATCell)& iList1, CATLISTP(CATCell)& iList2, double& ioDis);

	ExportedByCommonFuncMod HRESULT GetDistanceBetweenPointAndBody(CATMathPoint iPoint, CATBody_var& oBody, double& ioDis);

}

//-----------------------------------------------------------------------

#endif
