//===================================================================
// COPYRIGHT Tony 2016/11/22
//===================================================================
// MakeExcel.cpp
// Header definition of class MakeExcel
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2016/11/22 Creation: Code generated by the 3DS wizard
//===================================================================

#include "MakeExcel.h"
#include <iostream>
using std::cout;
using std::endl;

HRESULT Generate(const CATUnicodeString &ExcelName)
{
	HRESULT rc = S_OK;
	::CoInitialize(NULL);
	try{
		Excel::_ApplicationPtr pExcelApp;
		rc = pExcelApp.CreateInstance(L"Excel.Application");

		Excel::_WorkbookPtr pWorkBook = pExcelApp->Workbooks->Add();
		Excel::_WorksheetPtr pWorkSheet = pWorkBook->ActiveSheet;
		Excel::RangePtr pRange = pWorkSheet->Cells;
		/*pRange = pWorkSheet->GetRange(_bstr_t(L"A1"));*/
		pRange->Item[10][1] = L"xxxx";

		long irow = pWorkSheet->GetRange(_bstr_t(L"A65536"))->End[xlUp]->Row;
		cout<<"RowNumber: "<<irow<<endl;

		CATUnicodeString path = "E:\\";
		path.Append(ExcelName);
		_variant_t vPath = (LPCSTR)path.ConvertToChar();

		rc = pWorkBook->SaveAs(vPath,XlFileFormat::xlExcel8,vtMissing,vtMissing,vtMissing,vtMissing,XlSaveAsAccessMode::xlExclusive);
	
		pWorkBook->Close(VARIANT_TRUE);
		pExcelApp->Quit();
	}
	catch(_com_error e)
	{
		rc = E_FAIL;
		cout<<e.Description()<<endl;
	}

	return rc;
}


